---
- hosts: localhost
  connection: local
  tasks:
    - name: Clone the mongodb charts
      command: helm repo add bitnami https://charts.bitnami.com/bitnami
    - name: sleep for 20 seconds and continue with play
      wait_for:
        timeout: 20
      delegate_to: localhost
    - name: Installing mongodb
      command: helm install mongodb bitnami/mongodb --set service.type=LoadBalancer
   # - name: sleep for 200 seconds and continue with play
   #   wait_for:
   #     timeout: 200
   #   delegate_to: localhost
   # - name: Exposing root password for Mongodb (Username : root)
   #   command: kubectl get secret --namespace default mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode
   #   register: main
   # - debug:
   #     var: main
