---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating kafka-broker deployment
      k8s:
        state: present
        definition:
          kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: kafka-broker0
            namespace: default
          spec:
            selector:
              matchLabels:
                app: kafka
            template:
              metadata:
                labels:
                  app: kafka
                  id: "0"
              spec:
                containers:
                - name: kafka
                  image: wurstmeister/kafka
                  ports:
                  - containerPort: 9092
                  env:
                  - name: KAFKA_ADVERTISED_PORT
                    value: "30718"
                  - name: KAFKA_ADVERTISED_HOST_NAME
                    value: kafka-service
                  - name: KAFKA_ZOOKEEPER_CONNECT
                    value: zoo1:2181
                  - name: KAFKA_BROKER_ID
                    value: "0"
                  - name: KAFKA_CREATE_TOPICS
                    value: admintome-test:1:1
      register: main
    - debug:
        var: main
