---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating mints-env-api-service
      k8s:
        state: present
        definition:
          kind: Service
          apiVersion: v1
          metadata:
            name: test-env-api-service
            namespace: default
          spec:
            selector:
              app: test-env-api-service
            ports:
              - protocol: TCP
                #Port accessible inside cluster
                port: 5001
                # Port to forward to inside the pod
                targetPort: 5001
                #Port accessible outside cluster
                #reactappPort: 30567
            type: ClusterIP
    - name: Creating mints-env-api-deployment
      k8s:
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-env-api-service
            namespace: default
          spec:
            selector:
              matchLabels:
                app: test-env-api-service
            replicas: 1
            minReadySeconds: 15
            template:
              metadata:
                labels:
                  app: test-env-api-service
              spec:
                containers:
                  - name: test-env-api-service
                    image: msslabsbentonville/test-env-api:1099
                    imagePullPolicy: Always
                    #resources:
                    #requests:
                    #memory: "400Mi"
                    #cpu: "500m"
                    ports:
                      - containerPort: 5001
                        protocol: TCP
                    volumeMounts:
                      - name: routes
                        mountPath: /usr/src/app/data
                volumes:
                  - name: routes
                    persistentVolumeClaim:
                      claimName: data-camelapp
      register: mints
    - debug:
        var: mints

