apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    handler:
      slack:
        token: xoxb-2028381082244-2037457018646-ZAfthEiFFM0nCxVcFDGBGjAh
        channel: miracle-mss
    resource:
      deployment: true
      replicationcontroller: true
      replicaset: true
      daemonset: true
      services: true
      pod: true
Execute command:
