apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - image: tuna/kubewatch:v0.0.1
    imagePullPolicy: IfNotPresent
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  #- image: gcr.io/skippbox/kubectl:v1.3.0
   # args:
    #  - proxy
     # - "-p"
     # - "8080"
    #name: proxy
    #imagePullPolicy: IfNotPresent
  restartPolicy: Always
  serviceAccount: kubewatch
  serviceAccountName: kubewatch
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
