apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ibm-mq-psp
spec:
  allowPrivilegeEscalation: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
  - MKNOD
  allowedCapabilities:
  - SETPCAP
  - AUDIT_WRITE
  - CHOWN
  - NET_RAW
  - DAC_OVERRIDE
  - FOWNER
  - FSETID
  - KILL
  - SETUID
  - SETGID
  - NET_BIND_SERVICE
  - SYS_CHROOT
  - SETFCAP
  runAsUser:
    rule: RunAsAny
    rule: RunAsAny
  volumes:
  - secret
  - persistentVolumeClaim
  forbiddenSysctls:
  - '*'
