---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating kafka-service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kafka-service
            namespace: default
            labels:
              name: kafka
          spec:
            ports:
            - port: 9092
              name: kafka-port
              protocol: TCP
            selector:
              app: kafka
              id: "0"
            type: 
      register: main
    - debug:
        var: main 
