---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating zookeeper deployment
      k8s:
        state: present
        definition:
          kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: zookeeper-deployment-1
            namespace: default
          spec:
            selector:
              matchLabels:
                app: zookeeper-1
            template:
              metadata:
                labels:
                  app: zookeeper-1
              spec:
                containers:
                - name: zoo1
                  image: digitalwonderland/zookeeper
                  ports:
                  - containerPort: 2181
                  env:
                  - name: ZOOKEEPER_ID
                    value: "1"
                  - name: ZOOKEEPER_SERVER_1
                    value: zoo1
    - name: Creating mints-ui-api-service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: zoo1
            namespace: default
            labels:
              app: zookeeper-1
          spec:
            ports:
            - name: client
              port: 2181
              protocol: TCP
            - name: follower
              port: 2888
              protocol: TCP
            - name: leader
              port: 3888
              protocol: TCP
            selector:
              app: zookeeper-1
      register: main
    - debug:
        var: main 
