apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl  
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments", "replicasets"]
    verbs: ["get", "list", "delete", "rollout", "undo", "patch", "update", "watch"]     
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
  namespace: default
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
